apiVersion: v1
kind: ReplicationController
metadata:
  name: go-app-rc

spec:
  replicas: 3
  selector:
      app: go-app-label
  template:
    metadata:
      labels:
        app: go-app-label
    spec:
      containers:
        - name: go-app-container
          image: vishalbendre/my-first-go-ap
          ports:
          - containerPort: 8080